package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.PatientAdvocate;
import edu.ncsu.csc.iTrust2.models.User;

/**
 * Repository for interacting with Patient model. Method implementations
 * generated by Spring
 *
 * @author Kai Presler-Marshall
 * @param <T>
 *            Type of User
 *
 */
public interface PatientAdvocateRepository <T extends User> extends JpaRepository<PatientAdvocate, String> {

}
